export const MAX_APPLICATION_ATTACHMENT_MB = 5;
export const MAX_APPLICATION_ATTACHMENT_LABEL = `${MAX_APPLICATION_ATTACHMENT_MB}MB`;
export const MAX_APPLICATION_ATTACHMENT_BYTES = MAX_APPLICATION_ATTACHMENT_MB * 1024 * 1024;
export const MAX_APPLICATION_ATTACHMENT_BASE64_CHARS = Math.ceil(MAX_APPLICATION_ATTACHMENT_BYTES / 3) * 4;
